version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=odapython3
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./wait-for-it.sh -h db -p 3306 -t 0 && python3 django/manage.py migrate && python3 django/manage.py setup_oda && gunicorn --workers=4 --chdir django -b 0.0.0.0:8001 oda.wsgi"
    environment:
      - DJANGO_SETTINGS_MODULE=oda.settings.development
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/code
      - /code/web/node_modules
    ports:
      - "8000:8000"
  socket:
    build:
      context: .
      dockerfile: Dockerfile.socketapp
    command: bash -c "npm install && npm start"
    volumes:
      - .:/code
      - /code/socketapp/node_modules
    ports:
      - "8080:8080"
